version: '3'

services:

  mysql:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
     - ./data/mysql:/var/lib/mysql

  wordpress:
    image: leikir/wordpress:wordpress-5.5.1-php-7.2.30-apache
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
    ports:
      - 8000:80
    volumes:
      - ./data/wordpress/.htaccess:/var/www/html/.htaccess
      - ./data/wordpress/wp-content:/var/www/html/wp-content
      - ./wp-content/themes/smash:/var/www/html/wp-content/themes/smash
      - ./wordpress/php.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
